name: "Verify with KeY"

on:  
  push:
    branches: [ "main" ]
  pull_request:
  merge_group:
  
jobs:
  verify:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        java: [21]
        folder: [BinarySearch, ArrayList]
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'corretto'

      - name: Verify
        run: (cd ${{ matrix.folder }}; bash -xe prove.sh)
        